dist: trusty
sudo: required
language: node_js
node_js:
  - "12.13.0"
cache:
  yarn: true
  directories:
    - "node_modules"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn run init
script:
  - yarn run lint
  - yarn run type-check
  - yarn run test:integration
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_AUTH_TOKEN}" >> .npmrc
deploy:
  provider: script
  script:
    - yarn run publish-lerna-cutoff
  skip_cleanup: true
  on:
    tags: true
    branch: master